Repository viethoangat01/MAD12, pull requests merged in 2021-04, with the labels that each got.

#3 Login Layout
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_login_checkboxiconcheck.xml
  app/src/main/res/drawable/ic_login_checkboxoutline.xml
  app/src/main/res/drawable/ic_login_facebook.xml
  app/src/main/res/drawable/ic_login_googleplus.xml
  app/src/main/res/drawable/login_checkboxstyle.xml
  app/src/main/res/drawable/login_logo.png
  app/src/main/res/drawable/login_rectanglefacebook.xml
  app/src/main/res/drawable/login_rectanglegoogle.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation

#4 Feature: Layout Login
  app/src/main/res/drawable/ic_login_checkboxiconcheck.xml
  app/src/main/res/drawable/ic_login_checkboxoutline.xml
  app/src/main/res/drawable/ic_login_facebook.xml
  app/src/main/res/drawable/ic_login_googleplus.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#5 Home
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mad12/view/activity/MainActivity.java
  app/src/main/java/com/example/mad12/view/adapter/ViewPagerAdapter.java
  app/src/main/res/drawable/ic_homefragment_chemistry_60.xml
  app/src/main/res/drawable/ic_homefragment_english_60.xml
  app/src/main/res/drawable/ic_homefragment_geography_60.xml
  app/src/main/res/drawable/ic_homefragment_literature_60.xml
  app/src/main/res/drawable/ic_homefragment_math_60.xml
  app/src/main/res/drawable/ic_homefragment_physics_60.xml
  app/src/main/res/drawable/ic_linedocument_download_30.xml
  app/src/main/res/drawable/ic_main_document.xml
  app/src/main/res/drawable/ic_main_home.xml
  app/src/main/res/drawable/ic_main_menu_40.xml
  app/src/main/res/drawable/ic_main_notification.xml
  app/src/main/res/drawable/ic_main_selflearning.xml
  app/src/main/res/drawable/ic_main_user_40.xml
  app/src/main/res/drawable/ic_selflearningfragment_luyende_90.xml
  app/src/main/res/drawable/ic_selflearningfragment_ontheochude_90.xml
  app/src/main/res/drawable/ic_selflearningfragment_thionline_90.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_document.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_self_learning.xml
  app/src/main/res/layout/line_document.xml
  app/src/main/res/menu/main_menubottom.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: duplicate
